admin_default:
    path: /
    defaults: { _controller: DevyUkrBookBundle:Category:index }

devy_ukr_book_category:
    resource: "@DevyUkrBookBundle/Resources/config/routing/administration/category.yml"
    prefix:   /category

devy_ukr_book_post:
    resource: "@DevyUkrBookBundle/Resources/config/routing/administration/post.yml"
    prefix:   /post

devy_ukr_book_brand:
    resource: "@DevyUkrBookBundle/Resources/config/routing/administration/brand.yml"
    prefix:   /brand

devy_ukr_book_attribute:
    resource: "@DevyUkrBookBundle/Resources/config/routing/administration/attribute.yml"
    prefix:   /attribute

devy_ukr_book_product:
    resource: "@DevyUkrBookBundle/Resources/config/routing/administration/product.yml"
    prefix:   /product

devy_ukr_book_subscribers:
    resource: "@DevyUkrBookBundle/Resources/config/routing/administration/subscribers.yml"
    prefix:   /subscribers

devy_ukr_book_shopinfo:
    resource: "@DevyUkrBookBundle/Resources/config/routing/administration/shopinfo.yml"
    prefix:   /shop-info

devy_ukr_book_orders:
    resource: "@DevyUkrBookBundle/Resources/config/routing/administration/orders.yml"
    prefix:   /orders
