category:
    path:     /
    defaults: { _controller: "DevyUkrBookBundle:Category:index" }

category_show:
    path:     /{id}/show
    defaults: { _controller: "DevyUkrBookBundle:Category:show" }

category_new:
    path:     /new
    defaults: { _controller: "DevyUkrBookBundle:Category:new" }

category_new_child:
    path:     /{parent_id}/new
    defaults: { _controller: "DevyUkrBookBundle:Category:new" }
    requirements:
      parent_id: \d+

category_create:
    path:     /create
    defaults: { _controller: "DevyUkrBookBundle:Category:create" }
    requirements: { _method: post }

category_edit:
    path:     /{id}/edit
    defaults: { _controller: "DevyUkrBookBundle:Category:edit" }

category_update:
    path:     /{id}/update
    defaults: { _controller: "DevyUkrBookBundle:Category:update" }
    requirements: { _method: post|put }

category_delete:
    path:     /{id}/delete
    defaults: { _controller: "DevyUkrBookBundle:Category:delete" }
    requirements: { _method: post|delete }
